---
name: "Feature Request"
description: "Use this template for proposing new features"
title: "[Feature]: "
labels: [feature]

body:
  - type: markdown
    attributes:
      value: |
        ### **Description**
        Describe the task. What does this aim to implement?

  - type: textarea
    id: technical-details
    attributes:
      label: Technical Details
      description: |
        - Implementation details
        - Insight to what needs to be done
        - Etc.
    validations:
      required: false

  - type: textarea
    id: acceptance-criteria
    attributes:
      label: Acceptance Criteria
      description: |
        - Are metrics required?
        - Are translations required?
        - Cases to satisfy
        - XYZ should work
        - Etc.
        
        **Scenario: xxxx**
        - GIVEN a user is in x state  
        - WHEN a user does x  
        - AND a user does x  
        - THEN x should occur
    validations:
      required: false

  - type: textarea
    id: references
    attributes:
      label: References
      description: |
        - References go here.
        - Issue numbers. Links.
        - Slack threads.
        - Etc.
    validations:
      required: false
