name: Build, Lint, and Test

on:
  workflow_call:

env:
  SNAP_ENV: ${{ vars.SNAP_ENV }}
  PRICE_API_BASE_URL: ${{ vars.PRICE_API_BASE_URL }}
  STORE_PERMISSIONS_ENABLED: ${{ vars.STORE_PERMISSIONS_ENABLED }}
  USE_EOA_ACCOUNT: ${{ vars.USE_EOA_ACCOUNT }}
  ACCOUNT_API_BASE_URL: ${{ vars.ACCOUNT_API_BASE_URL }}
  SUPPORTED_CHAINS: ${{ vars.SUPPORTED_CHAINS }}

jobs:
  prepare:
    name: Prepare
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [21.x]
    outputs:
      child-workspace-package-names: ${{ steps.workspace-package-names.outputs.child-workspace-package-names }}
    steps:
      - name: Checkout and setup environment
        uses: MetaMask/action-checkout-and-setup@v1
        with:
          is-high-risk-environment: false
          cache-node-modules: ${{ matrix.node-version == '21.x' }}
      - name: Fetch workspace package names
        id: workspace-package-names
        run: |
          echo "child-workspace-package-names=$(yarn workspaces list --no-private --json | jq --slurp --raw-output 'map(.name) | @json')" >> "$GITHUB_OUTPUT"
        shell: bash

  validate-changelog:
    name: Validate changelog
    runs-on: ubuntu-latest
    needs:
      - prepare
    strategy:
      matrix:
        node-version: [21.x]
    steps:
      - name: Checkout and setup environment
        uses: MetaMask/action-checkout-and-setup@v1
        with:
          is-high-risk-environment: false
      - run: yarn changelog:validate
      - name: Require clean working directory
        shell: bash
        run: |
          if ! git diff --exit-code; then
            echo "Working tree dirty at end of job"
            exit 1
          fi

  build:
    name: Build
    runs-on: ubuntu-latest
    needs:
      - prepare
    strategy:
      matrix:
        node-version: [21.x]
    steps:
      - name: Checkout and setup environment
        uses: MetaMask/action-checkout-and-setup@v1
        with:
          is-high-risk-environment: false
      - run: yarn build
      - name: Cache permissions-kernel snap build
        uses: actions/cache@v4
        with:
          path: ./packages/permissions-kernel-snap/dist
          key: permissions-kernel-${{ runner.os }}-${{ github.sha }}
      - name: Cache gator-permissions snap build
        uses: actions/cache@v4
        with:
          path: ./packages/gator-permissions-snap/dist
          key: gator-permissions-${{ runner.os }}-${{ github.sha }}
      - name: Require clean working directory
        shell: bash
        run: |
          # Check if target branch is 'dev' and exclude snap.manifest.json files if so
          if [[ "${{ github.base_ref }}" == "dev" || "${{ github.ref_name }}" == "dev" ]]; then
            echo "Target branch is 'dev', ignoring changes to snap.manifest.json files"
            if ! git diff --exit-code -- . ':!**/snap.manifest.json'; then
              echo "Working tree dirty at end of job (excluding snap.manifest.json)"
              exit 1
            fi
          else
            if ! git diff --exit-code; then
              echo "Working tree dirty at end of job"
              exit 1
            fi
          fi

  lint:
    name: Lint
    runs-on: ubuntu-latest
    needs:
      - prepare
    strategy:
      matrix:
        node-version: [21.x]
    steps:
      - name: Checkout and setup environment
        uses: MetaMask/action-checkout-and-setup@v1
        with:
          is-high-risk-environment: false
      - run: yarn lint
      - name: Require clean working directory
        shell: bash
        run: |
          if ! git diff --exit-code; then
            echo "Working tree dirty at end of job"
            exit 1
          fi

  test:
    name: Test
    runs-on: ubuntu-latest
    needs:
      - prepare
      - build
    strategy:
      matrix:
        node-version: [21.x]
    steps:
      - name: Checkout and setup environment
        uses: MetaMask/action-checkout-and-setup@v1
        with:
          is-high-risk-environment: false
      - name: Restore permissions-kernel snap build cache
        uses: actions/cache@v4
        with:
          path: ./packages/permissions-kernel-snap/dist
          key: permissions-kernel-${{ runner.os }}-${{ github.sha }}
      - name: Restore gator-permissions snap build cache
        uses: actions/cache@v4
        with:
          path: ./packages/gator-permissions-snap/dist
          key: gator-permissions-${{ runner.os }}-${{ github.sha }}
      - name: Run e2e tests
        run: yarn test
      - name: Require clean working directory
        shell: bash
        run: |
          if ! git diff --exit-code; then
            echo "Working tree dirty at end of job"
            exit 1
          fi
