name: Publish Release

on:
  workflow_call:
    secrets:
      NPM_TOKEN:
        required: true
      SLACK_WEBHOOK_URL:
        required: true
env:
  SNAP_ENV: ${{ vars.SNAP_ENV }}
  PRICE_API_BASE_URL: ${{ vars.PRICE_API_BASE_URL }}
  STORE_PERMISSIONS_ENABLED: ${{ vars.STORE_PERMISSIONS_ENABLED }}
  ACCOUNT_API_BASE_URL: ${{ vars.ACCOUNT_API_BASE_URL }}
  TOKENS_API_BASE_URL: ${{ vars.TOKENS_API_BASE_URL }}
  GATOR_PERMISSIONS_PROVIDER_SNAP_ID: ${{ vars.GATOR_PERMISSIONS_PROVIDER_SNAP_ID }}
  MESSAGE_SIGNING_SNAP_ID: ${{ vars.MESSAGE_SIGNING_SNAP_ID }}
  KERNEL_SNAP_ID: ${{ vars.KERNEL_SNAP_ID }}
  SUPPORTED_CHAIN_IDS: ${{ vars.SUPPORTED_CHAIN_IDS }}

jobs:
  publish-release:
    name: Publish GitHub Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout and setup environment
        uses: MetaMask/action-checkout-and-setup@v1
        with:
          is-high-risk-environment: true
      - uses: MetaMask/action-publish-release@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: yarn build
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: publish-release-artifacts-${{ github.sha }}
          include-hidden-files: true
          retention-days: 4
          path: |
            ./packages/**/dist
            ./packages/**/snap.manifest.json
            ./node_modules/.yarn-state.yml

  publish-npm-dry-run:
    name: Dry run publish to NPM
    runs-on: ubuntu-latest
    needs: publish-release
    steps:
      - name: Checkout and setup environment
        uses: MetaMask/action-checkout-and-setup@v1
        with:
          is-high-risk-environment: true
          ref: ${{ github.sha }}
      - name: Restore build artifacts
        uses: actions/download-artifact@v4
        with:
          name: publish-release-artifacts-${{ github.sha }}
      - name: Dry run publish to NPM
        uses: MetaMask/action-npm-publish@v5
        with:
          slack-webhook-url: ${{ secrets.SLACK_WEBHOOK_URL }}
          subteam: S042S7RE4AE # @metamask-npm-publishers

  publish-npm:
    name: Publish to NPM
    environment: npm-publish
    runs-on: ubuntu-latest
    needs: publish-npm-dry-run
    steps:
      - name: Checkout and setup environment
        uses: MetaMask/action-checkout-and-setup@v1
        with:
          is-high-risk-environment: true
          ref: ${{ github.sha }}
      - name: Restore build artifacts
        uses: actions/download-artifact@v4
        with:
          name: publish-release-artifacts-${{ github.sha }}
      - name: Publish to NPM
        uses: MetaMask/action-npm-publish@v5
        with:
          npm-token: ${{ secrets.NPM_TOKEN }}
